# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36

# Network timeout settings
systemProp.http.socketTimeout=60000
systemProp.http.connectTimeout=60000
systemProp.https.socketTimeout=60000
systemProp.https.connectTimeout=60000
